version: '3'
services:
  api:
    image: hominhsangadvantech/back-end-k8s:v1
    build: .
    networks:
      - backend
    ports:
      - "8080:8080"
    # depends_on:
    #   - mongo

  # mongo:
  #   image: mongo
  #   volumes:
  #     - ./data:/data/db
  #   networks:
  #     - backend
  #   ports:
  #     - "27017:27017"

  web-cli:
    image: hominhsangadvantech/back-end:v2
    # links:
    #   - mongo
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
